### ISSUE TITLE
Import error related to libQt6Core.so.6

### ISSUE THREAD

**Issue by tomnewman86** [MattETurner/DFIRlogbook#3]
Hi Matt,

I'm getting an import error related to libQt6Core.so.6. Packages in requirements.txt have been installed without error.

Full traceback:
```
Traceback (most recent call last):
  File "DFIRlogbook.py", line 11, in <module>
    from PySide6 import QtCore, QtGui, QtWidgets
ImportError: libQt6Core.so.6: cannot open shared object file: No such file or directory
```

So far I've tried to resolve this (following some Googling) by:
`sudo apt update && apt upgrade`
`sudo apt install libsm6 libxrender1 libfontconfig1`
`sudo python3 -m pip install opencv-contrib-python`
`sudo python3 -m pip install opencv-python-headless`
`sudo apt update && apt upgrade`

But I'm still getting the same error.

I'm sure I've missed something obvious but any ideas?

Thanks

**Comment by MattETurner** [comment]
Hi, I was unsuccessful in reproducing this error. I tested with Ubuntu 20.04, python 3.8.10 (stock for this OS), and a PySide6 install via pip (6.2.2.1 as of writing this) without issue. Your issue sounds similar enough that this forum thread may be helpful in troubleshooting the problem. It may be that you are dealing with a mismatch in location, architecture, or absence: https://askubuntu.com/questions/1034313/ubuntu-18-4-libqt5core-so-5-cannot-open-shared-object-file-no-such-file-or-dir

Hope this helps!
-Matt
